CREATE TABLE [dbo].[UserTask]
(
	[Id] INT NOT NULL IDENTITY,
	[TaskId] INT NOT NULL,
	[UserId] INT NOT NULL,
	CONSTRAINT [PK_UserTask] PRIMARY KEY ([Id]),
	CONSTRAINT FK_UserTask_To_Users FOREIGN KEY ([UserId]) REFERENCES [Users]([Id]) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_UserTask_To_Tasks FOREIGN KEY ([TaskId]) REFERENCES [Tasks]([Id]) ON DELETE CASCADE ON UPDATE CASCADE,
)
